package edu.kit.ipasir4j.callback;

/**
 * A marker interface for classes generated by the {@link IpasirCallback @IpasirCallback} annotation.
 *
 * Should not be implemented by users of this library.
 */
public interface LearnCallbackMarker {
}
